<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="Masters in Financial Analysis at London Business School">
	<meta name="author" content="Mark Negodyuk">
	<meta name="generator" content="Hugo 0.75.1" />
	<title>Project 2 &middot; Mark Negodyuk: Porfolio Website</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong>Mark Negodyuk</strong> <span>Portfolio Website</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            
                <li><a href="/projects">Finance &amp; Economics</a></li>
            

        </ul>
        <ul class="actions vertical">
            
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Project 2</h1>
                            </header>
                            
                                <span class="image main"><img src="/img/projects/pic12.jpg" alt="" /></span>
                            
                            
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. We will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15...
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;f...
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9...
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;n...
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Afr...
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88...
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71....
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did n...
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did ...
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, ...
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5...
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, ...
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;...</code></pre>
<p>Before we carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
<pre class="r"><code>skim(yrbss)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>We will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, we describe the distribution of weights.</p>
<p>From the <code>skim()</code> function used previously we can see that 1004 values are missing from 13583 observations.</p>
<pre class="r"><code>we_yrb_cl &lt;- yrbss %&gt;% 
  filter(!is.na(weight)) 

we_yrb &lt;- we_yrb_cl %&gt;% 
  summarize(mean_w = mean(weight),
            sd_w = sd(weight),
            min_w = min(weight),
            median_w = median(weight),
            max_w = max(weight))

we_yrb</code></pre>
<pre><code>## # A tibble: 1 x 5
##   mean_w  sd_w min_w median_w max_w
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1   67.9  16.9  29.9     64.4  181.</code></pre>
<pre class="r"><code>ggplot(we_yrb_cl, aes(x = weight)) +
  geom_density() +
  labs(x = &quot;Weight in kilograms&quot;,
       y = &quot;&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Next, we consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<p>Let’s create a new variable <code>physical_3plus</code>, which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise:</p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;% 
  mutate(physical_3plus = ifelse(physically_active_7d &gt;= 3, &quot;yes&quot;, &quot;no&quot;))

yrbss %&gt;% filter(!is.na(physical_3plus)) %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(count = n()) %&gt;% 
  mutate(prop= count/sum(count))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   physical_3plus count  prop
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;
## 1 no              4404 0.331
## 2 yes             8906 0.669</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>CI_data &lt;- yrbss %&gt;% filter(!is.na(physical_3plus)) %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(count = n()) %&gt;% 
  mutate(prop = count/sum(count))

CI_act &lt;- c(mean = CI_data[1,3], se = sqrt(CI_data[1,3]*(1-CI_data[1,3])/(CI_data[1,2]+CI_data[2,2])))
paste0(&quot;95% CI for the population proportion of high school students who are NOT active 3 or more days per week is between &quot;, round(CI_act[[1]] - 1.96*CI_act[[2]],2), &quot; and &quot;, round(CI_act[[1]] + 1.96*CI_act[[2]],2))</code></pre>
<pre><code>## [1] &quot;95% CI for the population proportion of high school students who are NOT active 3 or more days per week is between 0.32 and 0.34&quot;</code></pre>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<p>We can see that the graphs are similar. We expected that the graph for lower activity would have a higher average weight, which is not the case in our graphs. Moreover, the graphs show the opposite effect where the graph for higher activity shows a slightly higher mean weight. However, the graph for the activity of under 3 days per week shows higher outliers on the top end of the graph, this may be the observations for those who are not active at all during the week and hence, have a higher weight.
One possible conclusion we can make from the graphs is that 3 days of activity a week may be sufficient for maintaining a healthy weight, and any activity above that may have no further effect on weight. Still such logic might be flawed by the fact that students with 3 days and more activity have more muscle mass, while students with lower activity are of the similar weight (or even lighter), but due to fat mass, which is less healthy.</p>
<pre class="r"><code>yrbss_w_p_cl &lt;- yrbss %&gt;% 
  filter(!is.na(weight), !is.na(physical_3plus)) %&gt;% 
  mutate(physical_3plus = case_when(
    physical_3plus == &quot;no&quot; ~ &quot;Active less than 3 days per week&quot;,
    TRUE ~ &quot;Active at least 3 days per week&quot;
  ))

ggplot(yrbss_w_p_cl, aes(x = weight)) +
  geom_boxplot() +
  facet_wrap(~ physical_3plus, ncol = 1) + 
  theme_minimal()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/boxplot-1.png" width="2400" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean/SD, etc weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>yrbss %&gt;%
  group_by(physical_3plus) %&gt;%
  filter(!is.na(physical_3plus)) %&gt;% 
  summarise(mean_weight = mean(weight, na.rm = TRUE),
            sd_weight = sd(weight, na.rm=TRUE),
            count = n(),
            se_weight = sd_weight/sqrt(count),
            t_critical = qt(0.975, count-1), 
            margin_of_error = t_critical * se_weight,
            lower = mean_weight - t_critical * se_weight,
            upper = mean_weight + t_critical * se_weight
            )</code></pre>
<pre><code>## # A tibble: 2 x 9
##   physical_3plus mean_weight sd_weight count se_weight t_critical
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 no                    66.7      17.6  4404     0.266       1.96
## 2 yes                   68.4      16.5  8906     0.175       1.96
## # ... with 3 more variables: margin_of_error &lt;dbl&gt;, lower &lt;dbl&gt;, upper &lt;dbl&gt;</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<p>h0 = There is no significant difference between weight for those who regularly exercise (&gt;3x per week) and those who do not. (Difference is equal to 0)
h1 = There is a difference between weight of those who regularly exercise (&gt;3x per week) and those who do not. (Difference is not equal to 0)</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>set.seed(888)

null_dist &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to “permute”, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-9-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77.</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-10-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<p><img src="C:/Users/Mark/Desktop/my_website/images/directors.png" width="100%" style="display: block; margin: auto;" /></p>
<p>First, I would like you to reproduce this graph. You may find <code>geom_errorbar()</code> and <code>geom_rect()</code> useful.</p>
<p>In addition, you will run a hpothesis test. You should use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<blockquote>
<p>Before anything, write down the null and alternative hypotheses, as well as the resulting test statistic and the associated t-stat or p-value. At the end of the day, what do you conclude?</p>
</blockquote>
<p>H0: Difference between the mean ratings of Tim Burton and Steven Spielberg is equal to 0
Ha: Difference between the mean ratings of Tim Burton and Steven Spielberg is NOT equal to 0</p>
<ol style="list-style-type: decimal">
<li>Calculate confidence intervals for each</li>
<li>See if CIs overlap</li>
<li>if yes =&gt; run t-test</li>
<li>if t &gt; 2 (approx. value) =&gt; REJECT H0</li>
</ol>
<p>We load the data and examine its structure</p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Ave...
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;...
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevor...
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015,...
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93...
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+0...
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+0...
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, ...
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658...
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752,...
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7....</code></pre>
<pre class="r"><code>stat_movies &lt;- movies %&gt;% 
  group_by(director) %&gt;% 
  summarise(mean_ratings = mean(rating),
            sd_ratings = sd(rating)) %&gt;% 
  filter(director == &quot;Tim Burton&quot;|director == &quot;Steven Spielberg&quot;)

ts_movies &lt;- movies %&gt;% 
  filter(director == &quot;Steven Spielberg&quot; | director == &quot;Tim Burton&quot;) %&gt;%
  group_by(director) %&gt;% 
  summarise(director = unique(director),
            r_mean = mean(rating),
            r_min = min(rating),
            r_max = max(rating),
            r_sd = sd(rating),
            num = n()) %&gt;% 
  mutate(r_se = r_sd/(sqrt(num))) %&gt;% 
  mutate(r_citop = r_mean+2*r_se, 
         r_cibot = r_mean-2*r_se)


ggplot(ts_movies, aes(y = r_mean, x = reorder(director, r_mean), colour = director)) +
  geom_errorbar(aes(ymin = r_cibot, ymax = r_citop), width=0.1, size = 1.25) +
  geom_pointrange(aes(ymin = r_cibot, ymax = r_citop), size = 1.25) +
  coord_flip() +
  theme_bw() +
  theme(legend.position = &quot;none&quot;) +
  geom_rect(aes(ymin = r_cibot[1], 
                ymax = r_citop[2], 
                xmin = -Inf, 
                xmax = Inf), 
                fill = &quot;grey&quot;, 
                color = &quot;NA&quot;,
                alpha = 0.3) +
  labs(y = &quot;Mean IMDB Rating&quot;,
       x = &quot;&quot;,
       title = &quot;Do Spielberg and Burton have the same mean IMDB rating?&quot;,
       subtitle = &quot;95% confidence intervals overlap&quot;) +
  geom_text(aes(label = round(r_citop,2), y = round(r_citop,2)), vjust = -1, col = &quot;black&quot;, size = 5) +
  geom_text(aes(label = round(r_cibot,2), y = round(r_cibot,2)), vjust = -1, col = &quot;black&quot;, size = 5) +
  geom_text(aes(label = round(r_mean,2), y = round(r_mean,2)), vjust = -1.5, col = &quot;black&quot;, size = 6) </code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-11-1.png" width="1800" style="display: block; margin: auto;" /></p>
<p>Now to the formal test calculations:</p>
<pre class="r"><code>set.seed(888)

# Create 95% CI
paste0(ts_movies$director, &quot;- CI: &quot;, round(ts_movies$r_cibot, 2), &quot; to &quot;, round(ts_movies$r_citop, 2))</code></pre>
<pre><code>## [1] &quot;Steven Spielberg- CI: 7.28 to 7.86&quot; &quot;Tim Burton- CI: 6.56 to 7.31&quot;</code></pre>
<pre class="r"><code># Run T-Test after grouping the movies data for the two directors only
grouped &lt;- movies %&gt;% 
  filter(director == &quot;Tim Burton&quot; | director == &quot;Steven Spielberg&quot;)

t.test(data = grouped, rating ~ director)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<pre class="r"><code># Calculating Difference in Means between Spielberg and Burton
obs_diff_mov &lt;- grouped %&gt;% 
  specify(rating ~ director) %&gt;% 
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

# Simulation of test with 1,000 repetitions
null_dist_mov &lt;- grouped %&gt;% 
  specify(rating ~ director) %&gt;% 
  hypothesise(null = &quot;independence&quot;)  %&gt;% 
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;% 
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

# Histogram of the observed values
ggplot(data = null_dist_mov, aes(x=stat)) + geom_histogram()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-12-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Visualise data on a two-sided histogram, showing the observed value
null_dist_mov %&gt;% 
  visualise() +
  shade_p_value(obs_stat = obs_diff_mov, direction = &quot;two_sided&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-12-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Calcualte P Value 
null_dist_mov %&gt;% 
  get_p_value(obs_stat = obs_diff_mov, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1    0.02</code></pre>
<p>The CIs of both directors overlap, however, the p-value is 0.01 (using data) and 0.02 (using bootstrap). Which shows statistical significance of the difference. Therefore, given this data, the null hypothesis is rejected on the 95% confidence level, i.e. on the 5% significance level there is statistical evidence of mean ratings of Steven Spielberg and Tim Burton being different.</p>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, ...
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, ...
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24...</code></pre>
</div>
<div id="relationship-salary-gender" class="section level2">
<h2>Relationship: Salary ~ Gender</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals
. Hypothesis testing
. Correlation analysis
. Regression</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
f_stat &lt;- mosaic::favstats (salary ~ gender, data=omega)

f_stat</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condfidence interval

gen_stat &lt;- f_stat %&gt;% 
  select(gender, mean, sd, n) %&gt;% 
  mutate(t_crit = qt(0.975, n-1),
         gen_se = sd/sqrt(n),
         gen_me = 1.96*gen_se,
         ci_bot = mean - gen_me,
         ci_top = mean + gen_me)

gen_stat</code></pre>
<pre><code>##   gender  mean   sd  n t_crit gen_se gen_me ci_bot ci_top
## 1 female 64543 7567 26   2.06   1484   2909  61634  67452
## 2   male 73239 7463 24   2.07   1523   2986  70253  76225</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. We show our hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package:</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(salary ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package

obs_diff &lt;- omega %&gt;%
  specify(salary ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

null_dist &lt;- omega %&gt;%
  specify(salary ~ gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/hypothesis_testing-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/hypothesis_testing-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;% get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
</div>
<div id="relationship-experience-gender" class="section level2">
<h2>Relationship: Experience ~ Gender</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
exp &lt;- favstats (experience ~ gender, data=omega)

exp</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<pre class="r"><code>exp_stat &lt;- exp %&gt;% 
  select(gender, mean, sd, n) %&gt;% 
  mutate(t_crit = qt(0.975, n-1),
         exp_se = sd/sqrt(n),
         exp_me = 1.96*exp_se,
         ci_bot = mean - exp_me,
         ci_top = mean + exp_me)

exp_stat</code></pre>
<pre><code>##   gender  mean    sd  n t_crit exp_se exp_me ci_bot ci_top
## 1 female  7.38  8.51 26   2.06   1.67   3.27   4.11   10.7
## 2   male 21.12 10.92 24   2.07   2.23   4.37  16.76   25.5</code></pre>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(experience ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code># hypothesis testing using infer package

obs_diff &lt;- omega %&gt;%
  specify(experience ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

null_dist &lt;- omega %&gt;%
  specify(experience ~ gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-14-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-14-2.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;% get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
</div>
<div id="relationship-salary-experience" class="section level2">
<h2>Relationship: Salary ~ Experience</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>ggplot(omega, aes(x = experience, y = salary, col = gender)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE) +
  scale_y_log10()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/projects/project2/index_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
</div>
</div>
<div id="challenge-1-yield-curve-inversion" class="section level1">
<h1>Challenge 1: Yield Curve inversion</h1>
<p>Every so often, we hear warnings from commentators on the “inverted yield curve” and its predictive power with respect to recessions. An explainer what a <a href="https://www.reuters.com/article/us-usa-economy-yieldcurve-explainer/explainer-what-is-an-inverted-yield-curve-idUSKBN1O50GA">inverted yield curve is can be found here</a>. If you’d rather listen to something, here is a great podcast from <a href="https://www.podbean.com/media/share/dir-4zgj9-6aefd11">NPR on yield curve indicators</a></p>
<p>In addition, many articles and commentators think that, e.g., <a href="https://www.bloomberg.com/news/articles/2019-08-14/u-k-yield-curve-inverts-for-first-time-since-financial-crisis"><em>Yield curve inversion is viewed as a harbinger of recession</em></a>. One can always doubt whether inversions are truly a harbinger of recessions, and <a href="https://twitter.com/5_min_macro/status/1161627360946511873">use the attached parable on yield curve inversions</a>.</p>
<p><img src="C:/Users/Mark/Desktop/my_website/images/yield_curve_parable.jpg" width="100%" style="display: block; margin: auto;" /></p>
<p>In our case we will look at US data and use the <a href="https://fred.stlouisfed.org/">FRED database</a> to download historical yield curve rates, and plot the yield curves since 1999 to see when the yield curves flatten. If you want to know more, a very nice article that explains the <a href="https://fredblog.stlouisfed.org/2018/10/the-data-behind-the-fear-of-yield-curve-inversions/">yield curve is and its inversion can be found here</a>. At the end of this challenge you should produce this chart</p>
<p><img src="C:/Users/Mark/Desktop/my_website/images/yield_curve_challenge.png" width="100%" style="display: block; margin: auto;" /></p>
<p>First, we will use the <code>tidyquant</code> package to download monthly rates for different durations.</p>
<pre class="r"><code># Get a list of FRED codes for US rates and US yield curve; choose monthly frequency
# to see, eg., the 3-month T-bill https://fred.stlouisfed.org/series/TB3MS
tickers &lt;- c(&#39;TB3MS&#39;, # 3-month Treasury bill (or T-bill)
             &#39;TB6MS&#39;, # 6-month
             &#39;GS1&#39;,   # 1-year
             &#39;GS2&#39;,   # 2-year, etc....
             &#39;GS3&#39;,
             &#39;GS5&#39;,
             &#39;GS7&#39;,
             &#39;GS10&#39;,
             &#39;GS20&#39;,
             &#39;GS30&#39;)  #.... all the way to the 30-year rate

# Turn  FRED codes to human readable variables
myvars &lt;- c(&#39;3-Month Treasury Bill&#39;,
            &#39;6-Month Treasury Bill&#39;,
            &#39;1-Year Treasury Rate&#39;,
            &#39;2-Year Treasury Rate&#39;,
            &#39;3-Year Treasury Rate&#39;,
            &#39;5-Year Treasury Rate&#39;,
            &#39;7-Year Treasury Rate&#39;,
            &#39;10-Year Treasury Rate&#39;,
            &#39;20-Year Treasury Rate&#39;,
            &#39;30-Year Treasury Rate&#39;)

maturity &lt;- c(&#39;3m&#39;, &#39;6m&#39;, &#39;1y&#39;, &#39;2y&#39;,&#39;3y&#39;,&#39;5y&#39;,&#39;7y&#39;,&#39;10y&#39;,&#39;20y&#39;,&#39;30y&#39;)

# by default R will sort these maturities alphabetically; but since we want
# to keep them in that exact order, we recast maturity as a factor 
# or categorical variable, with the levels defined as we want
maturity &lt;- factor(maturity, levels = maturity)

# Create a lookup dataset
mylookup&lt;-data.frame(symbol=tickers,var=myvars, maturity=maturity)
# Take a look:
mylookup %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">symbol</th>
<th align="left">var</th>
<th align="left">maturity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">TB3MS</td>
<td align="left">3-Month Treasury Bill</td>
<td align="left">3m</td>
</tr>
<tr class="even">
<td align="left">TB6MS</td>
<td align="left">6-Month Treasury Bill</td>
<td align="left">6m</td>
</tr>
<tr class="odd">
<td align="left">GS1</td>
<td align="left">1-Year Treasury Rate</td>
<td align="left">1y</td>
</tr>
<tr class="even">
<td align="left">GS2</td>
<td align="left">2-Year Treasury Rate</td>
<td align="left">2y</td>
</tr>
<tr class="odd">
<td align="left">GS3</td>
<td align="left">3-Year Treasury Rate</td>
<td align="left">3y</td>
</tr>
<tr class="even">
<td align="left">GS5</td>
<td align="left">5-Year Treasury Rate</td>
<td align="left">5y</td>
</tr>
<tr class="odd">
<td align="left">GS7</td>
<td align="left">7-Year Treasury Rate</td>
<td align="left">7y</td>
</tr>
<tr class="even">
<td align="left">GS10</td>
<td align="left">10-Year Treasury Rate</td>
<td align="left">10y</td>
</tr>
<tr class="odd">
<td align="left">GS20</td>
<td align="left">20-Year Treasury Rate</td>
<td align="left">20y</td>
</tr>
<tr class="even">
<td align="left">GS30</td>
<td align="left">30-Year Treasury Rate</td>
<td align="left">30y</td>
</tr>
</tbody>
</table>
<pre class="r"><code>df &lt;- tickers %&gt;% tidyquant::tq_get(get=&quot;economic.data&quot;, 
                   from=&quot;1960-01-01&quot;)   # start from January 1960

glimpse(df)</code></pre>
<pre><code>## Rows: 6,774
## Columns: 3
## $ symbol &lt;chr&gt; &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS...
## $ date   &lt;date&gt; 1960-01-01, 1960-02-01, 1960-03-01, 1960-04-01, 1960-05-01,...
## $ price  &lt;dbl&gt; 4.35, 3.96, 3.31, 3.23, 3.29, 2.46, 2.30, 2.30, 2.48, 2.30, ...</code></pre>
<p>Our dataframe <code>df</code> has three columns (variables):</p>
<ul>
<li><code>symbol</code>: the FRED database ticker symbol</li>
<li><code>date</code>: already a date object</li>
<li><code>price</code>: the actual yield on that date</li>
</ul>
<p>The first thing would be to join this dataframe <code>df</code> with the dataframe <code>mylookup</code> so we have a more readable version of maturities, durations, etc.</p>
<pre class="r"><code>yield_curve &lt;-left_join(df,mylookup,by=&quot;symbol&quot;) </code></pre>
<div id="plotting-the-yield-curve" class="section level2">
<h2>Plotting the yield curve</h2>
<p>This may seem long but it should be easy to produce the following three plots</p>
<div id="yields-on-us-rates-by-duration-since-1960" class="section level3">
<h3>Yields on US rates by duration since 1960</h3>
<p><img src="C:/Users/Mark/Desktop/my_website/images/yield_curve1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>yield_curve$var &lt;- factor(yield_curve$var, levels = c(&quot;3-Month Treasury Bill&quot;,
                                                      &quot;6-Month Treasury Bill&quot;,
                                                      &quot;1-Year Treasury Rate&quot;,
                                                      &quot;2-Year Treasury Rate&quot;,
                                                      &quot;3-Year Treasury Rate&quot;,
                                                      &quot;5-Year Treasury Rate&quot;,
                                                      &quot;7-Year Treasury Rate&quot;,
                                                      &quot;10-Year Treasury Rate&quot;,
                                                      &quot;20-Year Treasury Rate&quot;,
                                                      &quot;30-Year Treasury Rate&quot;))

ggplot(yield_curve, aes(x = date, y = price, col = var)) +
  geom_line() +
  facet_wrap(~var, ncol = 2) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;) +
  labs(x = &quot;&quot;,
       y = &quot;%&quot;,
       caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;,
       title = &quot;Yields on U.S. Treasury rates since 1960&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-15-1.png" width="2420" style="display: block; margin: auto;" /></p>
</div>
<div id="monthly-yields-on-us-rates-by-duration-since-1999-on-a-year-by-year-basis" class="section level3">
<h3>Monthly yields on US rates by duration since 1999 on a year-by-year basis</h3>
<p><img src="C:/Users/Mark/Desktop/my_website/images/yield_curve2.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>yield_curve_99 &lt;- yield_curve %&gt;% 
  filter(date &gt; ydm(19983112)) %&gt;% 
  mutate(year = year(date)) %&gt;% 
  mutate(day = format(date, format = &quot;%m-%d&quot;))

ggplot(yield_curve_99) +
  geom_line(aes(x = maturity, y = price, group = day, colour = factor(year))) +
  facet_wrap(~year, ncol = 4) +
  labs(x = &quot;Maturity&quot;,
       y = &quot;Yield(%)&quot;,
       title = &quot;US Yield Curve&quot;,
       caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-16-1.png" width="2420" style="display: block; margin: auto;" /></p>
</div>
<div id="month-and-10-year-yields-since-1999" class="section level3">
<h3>3-month and 10-year yields since 1999</h3>
<p><img src="C:/Users/Mark/Desktop/my_website/images/yield_curve3.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>yield_curve_99_spr &lt;- yield_curve_99 %&gt;% 
  filter(maturity == &quot;3m&quot; | maturity == &quot;10y&quot;)

ggplot(yield_curve_99_spr, aes(x = date, y = price, group = var, colour = var)) +
  geom_line() +
  theme_bw() +
  labs(x = &quot;&quot;,
       y = &quot;%&quot;,
       title = &quot;Yields on 3-Month and 10-Year US Treasury rates since 1999&quot;,
       caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;) +
  theme(legend.title = element_blank())</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-17-1.png" width="2640" style="display: block; margin: auto;" /></p>
<p>According to <a href="https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States">Wikipedia’s list of recession in the United States</a>, since 1999 there have been two recession in the US: between Mar 2001–Nov 2001 and between Dec 2007–June 2009. Does the yield curve seem to flatten before these recessions? Can a yield curve flattening really mean a recession is coming in the US? Since 1999, when did short-term (3 months) yield more than longer term (10 years) debt?</p>
<p>Besides calculating the spread (10year - 3months), there are a few things we need to do to produce our final plot</p>
<ul>
<li><p>Setup data for US recessions</p></li>
<li><p>Superimpose recessions as the grey areas in our plot</p></li>
<li><p>Plot the spread between 10 years and 3 months as a blue/red ribbon, based on whether the spread is positive (blue) or negative(red)</p></li>
<li><p>For the first, the code below creates a dataframe with all US recessions since 1946</p></li>
</ul>
<pre class="r"><code># get US recession dates after 1946 from Wikipedia 
# https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States

recessions &lt;- tibble(
  from = c(&quot;1960-04-01&quot;, &quot;1969-12-01&quot;, &quot;1973-11-01&quot;, &quot;1980-01-01&quot;,&quot;1981-07-01&quot;, &quot;1990-07-01&quot;, &quot;2001-03-01&quot;, &quot;2007-12-01&quot;),  
  to = c(&quot;1961-02-01&quot;, &quot;1970-11-01&quot;, &quot;1975-03-01&quot;, &quot;1980-07-01&quot;, &quot;1982-11-01&quot;, &quot;1991-03-01&quot;, &quot;2001-11-01&quot;, &quot;2009-06-01&quot;) 
  )  %&gt;% 
  mutate(From = ymd(from), 
         To=ymd(to),
         duration_days = To-From)

recessions</code></pre>
<pre><code>## # A tibble: 8 x 5
##   from       to         From       To         duration_days
##   &lt;chr&gt;      &lt;chr&gt;      &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;       
## 1 1960-04-01 1961-02-01 1960-04-01 1961-02-01 306 days     
## 2 1969-12-01 1970-11-01 1969-12-01 1970-11-01 335 days     
## 3 1973-11-01 1975-03-01 1973-11-01 1975-03-01 485 days     
## 4 1980-01-01 1980-07-01 1980-01-01 1980-07-01 182 days     
## 5 1981-07-01 1982-11-01 1981-07-01 1982-11-01 488 days     
## 6 1990-07-01 1991-03-01 1990-07-01 1991-03-01 243 days     
## 7 2001-03-01 2001-11-01 2001-03-01 2001-11-01 245 days     
## 8 2007-12-01 2009-06-01 2007-12-01 2009-06-01 548 days</code></pre>
<ul>
<li>To add the grey shaded areas corresponding to recessions, we use <code>geom_rect()</code></li>
<li>to colour the ribbons blue/red we must see whether the spread is positive or negative and then use <code>geom_ribbon()</code>. You should be familiar with this from last week’s homework on the excess weekly/monthly rentals of Santander Bikes in London.</li>
</ul>
<pre class="r"><code>## There is a way to create a needed table using base R and dplyr below
# ten_yield &lt;- yield_curve %&gt;% 
#   filter(maturity == &quot;10y&quot;) %&gt;% 
#   rename(ten_y = price)
# 
# yield_spread &lt;- yield_curve %&gt;% 
#   filter(maturity == &quot;3m&quot;) %&gt;% 
#   left_join(ten_yield, by = &quot;date&quot;) %&gt;% 
#   rename(three_m = price) %&gt;% 
#   mutate(diff = ten_y - three_m)

yield_spread &lt;- yield_curve %&gt;% 
  filter(maturity == &quot;3m&quot; | maturity  == &quot;10y&quot;) %&gt;% 
  subset(select = -c(symbol, maturity)) %&gt;%
  pivot_wider(values_from = price, names_from = var) %&gt;% 
  rename(ten_y = `10-Year Treasury Rate`,
         three_m = `3-Month Treasury Bill`) %&gt;% 
  mutate(diff = ten_y - three_m)

ggplot(yield_spread, aes(x = date, y = diff)) +
  geom_ribbon(aes(ymin = 0, ymax = pmax(diff,0)), fill = &quot;#4682B4&quot;, colour = &quot;black&quot;, alpha = 0.5) +
  geom_ribbon(aes(ymax = 0, ymin = pmin(diff,0)), fill = &quot;#ff3535&quot;, colour = &quot;black&quot;, alpha = 0.5) +
  geom_rect(data = recessions,
            inherit.aes = FALSE,
            aes(xmin = From, 
                xmax = To, 
                ymin = -Inf, 
                ymax = Inf), 
                fill = &quot;grey&quot;, 
                color = &quot;NA&quot;,
                alpha = 0.3) +
  geom_rug(color = ifelse(yield_spread$diff&gt;0, &quot;#4682B4&quot;, &quot;#ff3535&quot;), 
           size = 0.05, 
           length = unit(0.03, &quot;npc&quot;),
           sides = &quot;b&quot;) +
  theme_minimal() +
  theme(legend.position = &quot;none&quot;) +
  scale_x_date(date_breaks = &quot;2 years&quot;, date_labels = &quot;%Y&quot;, limits = as.Date(c(&#39;1959-01-01&#39;, &#39;2023-01-01&#39;), format=&quot;%Y-%M-%D&quot;)) +
  labs(x = &quot;&quot;,
       y = &quot;Difference (10 year - 3 month) yield in %&quot;,
       title = &quot;Yield Curve Inversion: 10-year minus 3-month Treasury rates&quot;,
       subtitle = &quot;Difference in % points monthly averages.\nShaded areas correspond to recessions&quot;,
       caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-18-1.png" width="2700" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="challenge-2gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2:GDP components over time and among countries</h1>
<p>At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">Wikipedia GDP page</a>.</p>
<p>The GDP data we will look at is from the <a href="https://unstats.un.org/unsd/snaama/Downloads">United Nations’ National Accounts Main Aggregates Database</a>, which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country’s GDP. The file we will work with is <a href="http://unstats.un.org/unsd/amaapi/api/file/6">GDP and its breakdown at constant 2010 prices in US Dollars</a> and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised</p>
<pre class="r"><code>UN_GDP_data  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=2) # Number of rows to skip</code></pre>
<p>The first thing you need to do is to tidy the data, as it is in wide format and you must make it into long, tidy format. Please express all figures in billions (divide values by <code>1e9</code>, or <span class="math inline">\(10^9\)</span>), and you want to rename the indicators into something shorter.</p>
<blockquote>
<p>make sure you remove <code>eval=FALSE</code> from the next chunk of R code– I have it there so I could knit the document</p>
</blockquote>
<pre class="r"><code>tidy_GDP_data  &lt;-  UN_GDP_data %&gt;% 
  pivot_longer(cols = 4:51, names_to = &quot;year&quot;, values_to = &quot;value&quot;) %&gt;% 
  mutate(value = value/(10^9)) %&gt;% 
  mutate(IndicatorName = case_when(
    IndicatorName == &quot;Gross Domestic Product (GDP)&quot; ~ &quot;Gross Domestic Product&quot;,
    IndicatorName == &quot;Imports of goods and services&quot; ~ &quot;Imports&quot;,
    IndicatorName == &quot;Exports of goods and services&quot; ~ &quot;Exports&quot;,
    IndicatorName == &quot;Gross capital formation&quot; ~ &quot;Gross capital formation&quot;,
    IndicatorName == &quot;General government final consumption expenditure&quot; ~ &quot;Government expenditure&quot;,
    IndicatorName == &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot; ~ &quot;Household expenditure&quot;,
    TRUE ~ NA_character_
  )) %&gt;% 
  filter(!is.na(IndicatorName)) %&gt;% 
  mutate(year = as.Date(year, format = &quot;%Y&quot;)) %&gt;%
  pivot_wider(values_from = &quot;value&quot;, names_from = &quot;IndicatorName&quot;)

glimpse(tidy_GDP_data)</code></pre>
<pre><code>## Rows: 10,560
## Columns: 9
## $ CountryID                 &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
## $ Country                   &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanista...
## $ year                      &lt;date&gt; 1970-10-20, 1971-10-20, 1972-10-20, 1973...
## $ `Household expenditure`   &lt;dbl&gt; 5.07, 4.84, 4.70, 5.21, 5.59, 5.65, 5.68,...
## $ `Government expenditure`  &lt;dbl&gt; 0.372, 0.382, 0.402, 0.421, 0.431, 0.598,...
## $ `Gross capital formation` &lt;dbl&gt; 0.985, 1.050, 0.919, 0.919, 1.181, 1.365,...
## $ Exports                   &lt;dbl&gt; 0.112, 0.145, 0.173, 0.218, 0.300, 0.316,...
## $ Imports                   &lt;dbl&gt; 0.184, 0.269, 0.260, 0.278, 0.407, 0.459,...
## $ `Gross Domestic Product`  &lt;dbl&gt; 10.72, 10.69, 8.94, 9.20, 9.70, 10.30, 10...</code></pre>
<pre class="r"><code># Let us compare GDP components for these 3 countries
country_list &lt;- c(&quot;United States&quot;,&quot;India&quot;, &quot;Germany&quot;)</code></pre>
<p>First, can you produce this plot?</p>
<p><img src="C:/Users/Mark/Desktop/my_website/images/gdp1.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>sel_GDP &lt;- tidy_GDP_data %&gt;% 
  filter(Country %in% country_list)

ggplot(sel_GDP, aes(x = year)) +
  geom_line(aes(y = `Gross capital formation`, col = &quot;#fa7575&quot;), size = 1) +
  geom_line(aes(y = `Government expenditure`, col = &quot;#0abd83&quot;), size = 1) +
  geom_line(aes(y = `Household expenditure`, col = &quot;#1bb2f1&quot;), size = 1) +
  geom_line(aes(y = `Imports`, col = &quot;#e870f0&quot;), size = 1) +
  geom_line(aes(y = `Exports`, col = &quot;#b5b74b&quot;), size = 1) +
  facet_wrap(~Country) +
  theme_bw() +
  scale_color_identity(name = &quot;Components of GDP&quot;,
                          breaks = c(&quot;#fa7575&quot;, &quot;#b5b74b&quot;, &quot;#0abd83&quot;, &quot;#1bb2f1&quot;, &quot;#e870f0&quot;),
                          labels = c(&quot;Gross capital formation&quot;, &quot;Exports&quot;, &quot;Government expenditure&quot;,
                                     &quot;Household expenditure&quot;, &quot;Imports&quot;),
                          guide = &quot;legend&quot;) +
  scale_x_date(date_breaks = &quot;10 years&quot;, date_labels = &quot;%Y&quot;) +
  labs(x = &quot;&quot;,
       y = &quot;Billion US$&quot;,
       title = &quot;GDP components over time&quot;,
       subtitle = &quot;In constant 2010 USD&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-19-1.png" width="2420" style="display: block; margin: auto;" /></p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<pre class="r"><code># calculate GDP two methods

GDP_comp &lt;- tidy_GDP_data %&gt;% 
  mutate(comp_GDP = Exports - Imports +`Gross capital formation`+`Government expenditure`+`Household expenditure`)</code></pre>
<blockquote>
<p>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</p>
</blockquote>
<p><img src="C:/Users/Mark/Desktop/my_website/images/gdp2.png" width="100%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>prop_GDP &lt;- GDP_comp %&gt;% 
  filter(Country %in% country_list) %&gt;% 
  mutate(Net_E = Exports - Imports) %&gt;% 
  mutate(GE_prop = `Government expenditure`/comp_GDP,
         Inv_prop = `Gross capital formation`/comp_GDP,
         C_prop = `Household expenditure`/comp_GDP,
         NE_prop = Net_E/comp_GDP)

ggplot(prop_GDP, aes(x = year)) +
  geom_line(aes(y = GE_prop, col = &quot;#fa7575&quot;), size = 1) +
  geom_line(aes(y = Inv_prop, col = &quot;#0abd83&quot;), size = 1) +
  geom_line(aes(y = C_prop, col = &quot;#1bb2f1&quot;), size = 1) +
  geom_line(aes(y = NE_prop, col = &quot;#e870f0&quot;), size = 1) +
  facet_wrap(~Country) +
  theme_bw() +
  scale_color_identity(name = &quot;&quot;,
                          breaks = c(&quot;#fa7575&quot;, &quot;#0abd83&quot;, &quot;#1bb2f1&quot;, &quot;#e870f0&quot;),
                          labels = c(&quot;Gross capital formation&quot;, &quot;Government expenditure&quot;,
                                     &quot;Household expenditure&quot;, &quot;Net Exports&quot;),
                          guide = &quot;legend&quot;) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = &quot;&quot;,
       y = &quot;proportion&quot;,
       title = &quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;,
       caption = &quot;Source: United Nations, https://unstats.un.org/unsd/snaama/Downloads&quot;)</code></pre>
<p><img src="/projects/project2/index_files/figure-html/unnamed-chunk-21-1.png" width="2420" style="display: block; margin: auto;" /></p>
<blockquote>
<p>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</p>
</blockquote>
<p>Firstly, we can see that household expenditure makes up the majority of GDP, around 60-70%. We can also see that gross capital formation and net exports have little variability over time contributing 15-20% and 0% respectively. Net exports tend to around or below 0% of GDP meaning that the 3 countries are on average net importers. Another observation is that for Germany and the US, gross capital formation and government expenditure contribute similar amounts to the GDP around 20%. While for India, government expenditure is a much bigger part of GDP (40% more recently) than gross capital formation (around 15%). This may suggest higher levels of Foreign Direct Investment as a proportion of GDP into Germany and the US, although for the US the proportion of gross capital formation has been falling throughout the period.</p>
<p>Of the 3 countries, we can see that Germany is the only one where net exports have consistently contributed positively to the GDP from the year 2000. We can also observe that the proportion of household spending has significantly fallen recently in India, with gross capital formation (investments) making up for the reduction, suggesting a slowdown in welfare growth and the investment stimulus. We can also see that household spending in the US has been on the rise while net exports have declined recently. This could suggest higher domestic production of certain goods and services and possible even higher imports by the US, compared to exports.</p>
<blockquote>
<p>If you want to, please change <code>country_list &lt;- c("United States","India", "Germany")</code> to include your own country and compare it with any two other countries you like</p>
</blockquote>
<p>We decided to use the default countries to fully replicate the analysis</p>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://www.facebook.com/mark.negodyuk" class="icon alt fa-facebook" target="_blank"><span class="label">Facebook</span></a></li>
                
                    <li><a href="https://www.instagram.com/negomark" class="icon alt fa-instagram" target="_blank"><span class="label">Instagram</span></a></li>
                
                    <li><a href="https://www.github.com/MNegodyuk" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com/in/mnegodyuk" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; MNegodyuk</li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
